- name: line in file example
  hosts: all
  become: true
  tasks:
    - name: line in file
      lineinfile:
        path: /var/www/html/index.html
        regexp: '<h1>'
        line: 'my batch is ansible devops'      
 
    - name: block in file
      blockinfile:
        path: /var/www/html/index.html
        block: 
          <h1> hello world this is cloudblitz </h1>
          
 