- name: line in file example
  hosts: all
  tasks:
    - name: line in file
      lineinfile:
        path: /var/www/html/index.html
        regexp: '^<h1> hello world, Welcome to Cloudblitz </h1>'
        line: "<h1>my batch is ansible devops </h1>"        

    - name: line in file
      lineinfile:
        path: /var/www/html/index.html
        regexp: '^my'
        state: absent

    - name: block in file
      blockinfile:
        path: /var/www/html/index.html
        block: |  
          <h1> hello world, Welcome to Cloudblitz </h1>
          <h2> My name is DATTA </h2>
          <h3> This is DevOps Batch </h3>
