- name: line in file example
  hosts: all
  tasks:
    - name: line in file
      lineinfile:
        path: /var/www/html/index.html
        regexp: '^<h1> hello world, welcome to Cloudblitz </h1>'
        line: "my batch is ansible devops</h1>"        
