- name: variable example
  hosts: all
  vars:
    URL: "cbz.google.com"  
  tasks: 
    - name: print url
      debug: 
        msg: "{{ URL }}"

    - name: print 2nd url
      debug: 
        msg: "{{ URL }}"  
      vars: 
        URL: "local.google.com"
    - name: print 3rd url
    
      debug: 
        msg: "{{ URL }}" 