- name: variable example
  hosts: all
  vars:
    URl: "cbz.google.com"  
  tasks: 
    - name: print url
      debug: 
        msg: "{{URL}}"

    - name: print another url
      debug: 
        msg: "{{URL}}"