- name: gathering facts
  hosts: all
  tasks:
      - name: print OS
        debug:
          msg: "{{ ansible_distribution }}"

      - name: print IP
        debug:
          msg: "{{ hw_timestamp_filters.ipv4.address }}"
    