- name: register demo
  hosts: all
  tasks:
    - name: get hostname
      shell: 
        arg: hostname
      register: URL
      ignore_errors: true
    
    - name: print hostname
      debug:
        msg: "Hello World"
      ignore_errors: true

    - name: print IP
      debug:
        msg: "10.0.0"