- name: register demo
  hosts: all
  tasks:
    - name: get hostname
      shell: 
        arg: hostname
      register: URL
      
    
  
    - name: print hostname
      debug:
        msg: "Hello World"
