- name: privilege escalation Example
  hosts: all
  become: true
  tasks:
    - name: install http
      yum:
        name: httpd
        state: latest
      when: ansible_os_family  == "RedHat"
    
    - name: install apache2
      apt:
        name: apache2
        state: latest
      when: ansible_os_family  == "Debian"
