- name: loop example
  hosts: all
  become: true
  tasks:
    - name: print fruit list
      debug:
        msg: "{{ item }}"
      loop:
        - banana
        - apple
        - mango
        - straberry
    
    - name: install git wget httpd vim nginx
      yum:
        name: "{{item}}"
        state: latest
      loop:
        - git
        - wget
        - httpd
        - vim
        - nginx
