- name: loop example
  hosts: all
  become: true
  tasks:
    - name: print fruit list
      debug:
        msg: "{{ item }}"
      loop:
        - banana
        - apple
        - mango
        - straberry
    
    
