- name: install java
  yum:
    name: java-11-openjdk
    state: latest

- name: download tomcat 
  get_url: "{{URL}}"
  dest: /opt

- name: extract tomcat
  archive:
  src: {{ TOMCAT }}
  dest: /opt

- name: start tomcat
  shell: /opt/{{ TOMCAT_DIR}}/bin/catalina.sh start