- name: install java
  yum:
    name: java-11-openjdk
    state: latest

- name: download tomcat 
  get_url: "{{URL}}"
  dest: /opt

- name: extract tomcat
  archive:
  src: {{apache-tomcat-8.5.90.tar.gz}}
  dest: /opt
