- name: install java
  yum:
    name: java-11-openjdk
    state: latest

- name: download tomcat 
  get_url:
    url: "{{ URL }}"
    dest: /opt

- name: extract tomcat
  unarchive:
    src: "{{ URL }}"
    dest: /opt
    remote_src: true


- name: start tomcat
  shell: /opt/{{ TOMCAT_DIR }}/bin/catalina.sh run  