- name: install java
  yum:
    name: java-11-openjdk
    state: latest

- name: download tomcat 
  get_url:
  #  dest: /opt

- name: extract tomcat
  unarchive:
    src: "{{ URL }}"
    dest: /opt
    remote_src: true

- name: upload tomcat daemon
  copy:
    src: tomcat-init
    dest: /etc/init.d/tomcatd
    mode: 0755
  notify: 
    - restart tomcat

- name: deploy application
  get_url:
    url: http://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest: /opt/{{TOMCAT_DIR}}/webapps/


#- name: start tomcat
#  shell: /opt/{{ TOMCAT_DIR }}/bin/catalina.sh run  