- name: install httpd
  become: true
  package: 
    name: " PKG "
    state: present

- name: deploy application
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start service  
  systemd: 
    name:
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mystatefulset
    spec:
      selector:
        matchLabels:
          app: myapp
      serviceName: <ServiceName>
      replicas: 2
      template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
          - name: myapp
            image: registry.k8s.io/nginx-slim:0.8
            ports:
            - containerPort: 80
              name: web
            volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: www
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
    
