- name: install httpd
  become: true
  package: 
    name: " PKG "
    state: present

- name: deploy application
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start apiVersion: v1
kind: Service
metadata
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
