- name: install httpd
  package: 
    name: "{{PKG}}"
    state: present

- name: proxy conf
  copy:
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf
  notify: 
    - restart service


- name: deploy application
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start service  
  systemd: 
    name: " {{PKG}} "
    state: restarted
    enabled: true