- name: install httpd
  yum: 
    name: httpd
    state: present

- name: deploy application
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start service
  systemd:
    name: httpd
    state: started
    enabled: true
